### ISSUE TITLE
Docs: Add Comments/Docs to pom.xml file

### ISSUE THREAD

**Issue by usmanIITR** [mdgspace/activity-leaderboard-backend#18]
add comments suggesting the uses of dependencies and plugins used.

**Comment by Ayush0Chaudhary** [comment]
Cool go ahead!

**Comment by usmanIITR** [comment]
also, we can add comments in application.properties file!

**Comment by Ayush0Chaudhary** [comment]
https://github.com/mdgspace/activity-leaderboard-backend/pull/19

completed so closing
