### ISSUE TITLE
Add "Target" directory to gitignore

### ISSUE THREAD

**Issue by usmanIITR** [mdgspace/activity-leaderboard-backend#21]
**Describe the bug**
'target' directory is an auto generated directory on building the project. As a result, it contains conflicting files.

**Comment by usmanIITR** [comment]
i want to work on this issue.

**Comment by Ayush0Chaudhary** [comment]
You can work on it, also delete the entire folder target.

here is the sample .gitignore for spring boot
https://github.com/xkcoding/spring-boot-demo/blob/master/demo-helloworld/.gitignore

**Comment by Ayush0Chaudhary** [comment]
the official 
https://github.com/spring-projects/spring-boot/blob/main/.gitignore

**Comment by usmanIITR** [comment]
on it, Thanks

**Comment by Ayush0Chaudhary** [comment]
completed
